baseURL = 'https://fchibana.github.io/'
languageCode = 'en-us'
title = 'Fabio Chibana'
theme = 'PaperMod'
[params]
# AuthorName = 'Fabio'
author = 'Fabio'

[params.homeInfoParams]
  Title = "Hi there yo! 👋"
  Content = "Welcome to my website"

#   [[params.socialIcons]]
#   name = "twitter"
#   url = "https://twitter.com/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/fchibana"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/fabio-chibana/"

[menu]
[[menu.main]]
    name = 'Posts'
    pageRef = '/'
    weight = 10
[[menu.main]]
    name = 'Portfolio'
    pageRef = '/portfolio'
    weight = 20
[[menu.main]]
    name = 'About Me'
    pageRef = '/About'
    weight = 30
